from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    import argparse


class _SubparserGroup(Protocol):
    def add_parser(self, name: str) -> argparse.ArgumentParser: ...


def add_integration_parsers(subparsers: _SubparserGroup) -> None:
    _add_classcard_parser(subparsers)
    _add_gws_parser(subparsers)
    _add_kakao_parser(subparsers)


def _add_gws_parser(subparsers: _SubparserGroup) -> None:
    gws = subparsers.add_parser("gws")
    sub = gws.add_subparsers(dest="gws_command", required=True)
    setup = sub.add_parser("setup")
    _ = setup.add_argument("--client-file")
    _ = setup.add_argument("--token-file")
    _ = setup.add_argument("--json", action="store_true")
    status = sub.add_parser("status")
    _ = status.add_argument("--token-file")
    _ = status.add_argument("--json", action="store_true")
    client = sub.add_parser("client")
    _ = client.add_argument("client_verb", choices=["install"])
    _ = client.add_argument("--downloads")
    _ = client.add_argument("--to")
    _ = client.add_argument("--json", action="store_true")
    calendar = sub.add_parser("calendar")
    _ = calendar.add_argument("calendar_verb", choices=["list", "create-event"])
    _ = calendar.add_argument("--from", dest="time_from")
    _ = calendar.add_argument("--to", dest="time_to")
    _ = calendar.add_argument("--title")
    _ = calendar.add_argument("--start")
    _ = calendar.add_argument("--end")
    _ = calendar.add_argument("--description")
    _ = calendar.add_argument("--token-file")
    _ = calendar.add_argument("--json", action="store_true")
    drive = sub.add_parser("drive")
    _ = drive.add_argument("drive_verb", choices=["upload"])
    _ = drive.add_argument("--file", required=True)
    _ = drive.add_argument("--folder-name")
    _ = drive.add_argument("--token-file")
    _ = drive.add_argument("--json", action="store_true")
    sheets = sub.add_parser("sheets")
    _ = sheets.add_argument(
        "sheets_verb",
        choices=[
            "create",
            "append",
            "update",
            "clear",
            "batch-update",
            "batch-clear",
            "values-get",
        ],
    )
    _ = sheets.add_argument("--title")
    _ = sheets.add_argument("--sheet-id")
    _ = sheets.add_argument("--range")
    _ = sheets.add_argument("--from-tsv")
    _ = sheets.add_argument("--from-json")
    _ = sheets.add_argument("--out")
    _ = sheets.add_argument("--token-file")
    _ = sheets.add_argument("--json", action="store_true")
    gmail = sub.add_parser("gmail")
    _ = gmail.add_argument("gmail_verb", choices=["send"])
    _ = gmail.add_argument("--to", required=True)
    _ = gmail.add_argument("--subject", required=True)
    _ = gmail.add_argument("--body-file", required=True)
    _ = gmail.add_argument("--attach")
    _ = gmail.add_argument("--approval-id")
    _ = gmail.add_argument("--token-file")
    _ = gmail.add_argument("--json", action="store_true")
    _add_profile_args(gmail)


def _add_classcard_parser(subparsers: _SubparserGroup) -> None:
    classcard = subparsers.add_parser("classcard")
    sub = classcard.add_subparsers(dest="classcard_command", required=True)
    login = sub.add_parser("login")
    _ = login.add_argument("--username")
    _ = login.add_argument("--password")
    _ = login.add_argument("--json", action="store_true")
    direct = sub.add_parser("direct-upload")
    _ = direct.add_argument("--checkpoint", required=True)
    _ = direct.add_argument("--class-url", required=True)
    _ = direct.add_argument("--credentials")
    _ = direct.add_argument("--profile-dir")
    _ = direct.add_argument("--json", action="store_true")
    repair = sub.add_parser("direct-repair-audio")
    _ = repair.add_argument("--set-id", required=True)
    _ = repair.add_argument("--credentials")
    _ = repair.add_argument("--profile-dir")
    _ = repair.add_argument("--json", action="store_true")
    upload = sub.add_parser("upload")
    _ = upload.add_argument("--student", required=True)
    _ = upload.add_argument("--db")
    _ = upload.add_argument("--checkpoint")
    _ = upload.add_argument("--lesson-date")
    _ = upload.add_argument(
        "--mode",
        choices=["all", "전체", "n_days", "n일", "daily", "ab_repeat", "ab반복", "repeat"],
    )
    _ = upload.add_argument("--span-days", type=int)
    _ = upload.add_argument("--out-dir")
    _ = upload.add_argument("--execute", action="store_true")
    _ = upload.add_argument("--headed", action="store_true")
    _ = upload.add_argument("--profile-dir")
    _ = upload.add_argument("--slow-mo-ms", type=int)
    _ = upload.add_argument("--json", action="store_true")
    _add_profile_args(upload)
    recover = sub.add_parser("recover")
    _ = recover.add_argument("--checkpoint", required=True)
    _ = recover.add_argument("--execute", action="store_true")
    _ = recover.add_argument("--headed", action="store_true")
    _ = recover.add_argument("--profile-dir")
    _ = recover.add_argument("--slow-mo-ms", type=int)
    _ = recover.add_argument("--json", action="store_true")
    _add_profile_args(recover)
    verify = sub.add_parser("verify")
    _ = verify.add_argument("--checkpoint", required=True)
    _ = verify.add_argument("--class-url", required=True)
    _ = verify.add_argument("--headed", action="store_true")
    _ = verify.add_argument("--profile-dir")
    _ = verify.add_argument("--slow-mo-ms", type=int)
    _ = verify.add_argument("--json", action="store_true")
    _add_profile_args(verify)
    _add_classcard_study_parser(sub)


def _add_classcard_study_parser(sub: _SubparserGroup) -> None:
    study = sub.add_parser("study")
    study_sub = study.add_subparsers(dest="classcard_study_command", required=True)
    study_import = study_sub.add_parser("import")
    _ = study_import.add_argument("--student", required=True)
    _ = study_import.add_argument("--from", dest="from_path", required=True)
    _ = study_import.add_argument("--date", required=True)
    _ = study_import.add_argument("--lesson-date")
    _ = study_import.add_argument("--source-label")
    _ = study_import.add_argument("--create-missing-words", action="store_true")
    _ = study_import.add_argument("--dry-run", action="store_true")
    _ = study_import.add_argument("--db")
    _ = study_import.add_argument("--json", action="store_true")
    _add_profile_args(study_import)
    study_summary = study_sub.add_parser("summary")
    _ = study_summary.add_argument("--student")
    _ = study_summary.add_argument("--limit", type=int)
    _ = study_summary.add_argument("--mastery-threshold", type=int)
    _ = study_summary.add_argument("--db")
    _ = study_summary.add_argument("--json", action="store_true")
    _add_profile_args(study_summary)
    study_due = study_sub.add_parser("due")
    _ = study_due.add_argument("--student", required=True)
    _ = study_due.add_argument("--limit", type=int)
    _ = study_due.add_argument("--mastery-threshold", type=int)
    _ = study_due.add_argument("--db")
    _ = study_due.add_argument("--json", action="store_true")
    _add_profile_args(study_due)
    study_live = study_sub.add_parser("live")
    _ = study_live.add_argument("--student")
    _ = study_live.add_argument("--limit", type=int)
    _ = study_live.add_argument("--class-url")
    _ = study_live.add_argument("--credentials")
    _ = study_live.add_argument("--profile-dir")
    _ = study_live.add_argument("--db")
    _ = study_live.add_argument("--json", action="store_true")
    _add_profile_args(study_live)


def _add_kakao_parser(subparsers: _SubparserGroup) -> None:
    kakao = subparsers.add_parser("kakao")
    sub = kakao.add_subparsers(dest="kakao_command", required=True)
    login = sub.add_parser("login")
    _ = login.add_argument("--headed", action="store_true")
    _ = login.add_argument("--admin-url")
    _ = login.add_argument("--json", action="store_true")
    _add_profile_args(login)
    calibrate = sub.add_parser("calibrate")
    _ = calibrate.add_argument("--json", action="store_true")
    _add_profile_args(calibrate)
    status = sub.add_parser("status")
    _ = status.add_argument("--json", action="store_true")
    _add_profile_args(status)
    send = sub.add_parser("send-friend")
    _ = send.add_argument("--message")
    _ = send.add_argument("--body-file")
    _ = send.add_argument("--image")
    _ = send.add_argument("--group")
    _ = send.add_argument("--approval-id")
    _ = send.add_argument("--max")
    _ = send.add_argument("--json", action="store_true")
    _add_profile_args(send)
    chats = sub.add_parser("chats")
    chat_sub = chats.add_subparsers(dest="kakao_chats_command", required=True)
    pull = chat_sub.add_parser("pull")
    _ = pull.add_argument("--admin-url")
    _ = pull.add_argument("--headed", action="store_true")
    _ = pull.add_argument("--json", action="store_true")
    _add_profile_args(pull)
    reply = chat_sub.add_parser("reply")
    _ = reply.add_argument("--contact", required=True)
    _ = reply.add_argument("--message", required=True)
    _ = reply.add_argument("--approval-id")
    _ = reply.add_argument("--admin-url")
    _ = reply.add_argument("--headed", action="store_true")
    _ = reply.add_argument("--json", action="store_true")
    _add_profile_args(reply)
    for name in ("history", "summary"):
        command = sub.add_parser(name)
        _ = command.add_argument("--contact", required=True)
        _ = command.add_argument("--json", action="store_true")
        _add_profile_args(command)


def _add_profile_args(parser: argparse.ArgumentParser) -> None:
    _ = parser.add_argument("--profile-root")
    _ = parser.add_argument("--profile")
